module: MaterialMotionDirectManipulation
module_version: 1.1.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotionDirectManipulation.xcworkspace
  - -scheme
  - MaterialMotionDirectManipulation
github_url: https://github.com/material-motion/direct-manipulation-swift
github_file_prefix: https://github.com/material-motion/direct-manipulation-swift/tree/v1.1.0
